apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
      - name: auth-backend
        image: "{{ .Values.authBackend.image.repository }}:{{ .Values.authBackend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://4.tcp.eu.ngrok.io:16536/postgres?currentSchema=auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: auth-backend
