apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezcharge-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ezcharge-backend
  template:
    metadata:
      labels:
        app: ezcharge-backend
    spec:
      containers:
      - name: ezcharge-backend
        image: "{{ .Values.ezchargeBackend.image.repository }}:{{ .Values.ezchargeBackend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://chubby-pens-yawn.loca.lt/ezcharge
---
apiVersion: v1
kind: Service
metadata:
  name: ezcharge-backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: ezcharge-backend
